// Generated by CodiumAI

describe('ChatPage', () => {

    // Renders the conversation list and message container components
    it('should render the conversation list and message container components', () => {
      // Initialize and invoke the ChatPage function
      const wrapper = shallow(<ChatPage />);

      // Assert that the Conversation component is rendered
      expect(wrapper.find(Conversation)).toHaveLength(1);

      // Assert that the MessageContainer component is rendered
      expect(wrapper.find(MessageContainer)).toHaveLength(1);
    });

    // Handles empty conversation list
    it('should handle empty conversation list', () => {
      // Initialize and invoke the ChatPage function with empty conversations
      const wrapper = shallow(<ChatPage conversations={[]} />);

      // Assert that the Conversation component is not rendered
      expect(wrapper.find(Conversation)).toHaveLength(0);

      // Assert that the MessageContainer component is rendered
      expect(wrapper.find(MessageContainer)).toHaveLength(1);
    });
});
